USE BD_TARJETA;
GO

-- TABLE CREATION
CREATE TABLE LOGS(

	ID INT IDENTITY(1,1) PRIMARY KEY ,  
	ORIGIN NVARCHAR(100) NOT NULL,
	LOG_DESCRIPTION NVARCHAR(600) NULL,
	LOG_DT  DATETIME2 DEFAULT GETDATE()
);

CREATE TABLE DOCTYPE(

	ID INT IDENTITY(1,1) PRIMARY KEY,
	DOCNAME NVARCHAR(30) NOT NULL

);

CREATE TABLE TRANSACTION_STATE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TSTATE NVARCHAR(50) NOT NULL
);

CREATE TABLE CLIENT(
	DOC_NUMBER NVARCHAR(20) NOT NULL PRIMARY KEY,
	CLIENT_NAME NVARCHAR(250) NOT NULL,
	CELLPHONE NVARCHAR(100) NULL,
	EMAIL NVARCHAR(200) NULL,
	CREATION_DATE  DATETIME2 DEFAULT GETDATE(),
	CREATION_USER NVARCHAR(100) DEFAULT 'SYSTEM',
	ID_DOCTYPE INT NOT NULL,
	CONSTRAINT FK_CLIENT_DOCTYPE FOREIGN KEY (ID_DOCTYPE) REFERENCES DOCTYPE(ID)
);



CREATE TABLE CARDS(

	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	ID_CLIENT NVARCHAR(20) NOT NULL,
	CARD_NUMBER NVARCHAR(20) NOT NULL,
	LASTD_CARD VARCHAR(4) NOT NULL,
	CREDIT_LIMIT DECIMAL(18,2) NOT NULL,
	AV_CREDIT DECIMAL(18,2) NOT NULL,
	TOTAL_CREDIT DECIMAL(18,2) NOT NULL,
	INTEREST DECIMAL(18,2) DEFAULT 9.0,
	MIN_INTEREST DECIMAL(18,2) DEFAULT 5.0,
	CREATION_DATE DATETIME2 DEFAULT GETDATE(),
	CREATION_USER VARCHAR(100) DEFAULT 'SYSTEM'
	CONSTRAINT FK_ID_CLIENTE_CC FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(DOC_NUMBER)

)


CREATE TABLE MOVEMENTS_TC(

	ID INT IDENTITY(1,1) PRIMARY KEY,
	MV_DATE DATETIME2 NOT NULL DEFAULT GETDATE(),
	ID_CARD UNIQUEIDENTIFIER NOT NULL, 
	AMOUNT DECIMAL(18,2) NOT NULL,
	MV_DESCRIPTION NVARCHAR(300) NULL,
	ID_STATE INT NOT NULL,
	CONSTRAINT FK_ID_STATE_MV FOREIGN KEY(ID_STATE) REFERENCES TRANSACTION_STATE(ID),
	CONSTRAINT FK_ID_CARD_MV FOREIGN KEY(ID_CARD) REFERENCES CARDS(ID)

);

CREATE TABLE PAYMENTS_TC(

	ID INT IDENTITY(1,1) PRIMARY KEY,
	MV_DATE DATETIME2 NOT NULL DEFAULT GETDATE(),
	ID_CARD UNIQUEIDENTIFIER NOT NULL, 
	AMOUNT DECIMAL(18,2) NOT NULL,
	MV_DESCRIPTION NVARCHAR(300) NULL,
	ID_STATE INT NOT NULL,
	CONSTRAINT FK_ID_STATE_PY FOREIGN KEY(ID_STATE) REFERENCES TRANSACTION_STATE(ID),
	CONSTRAINT FK_ID_CARD_PY FOREIGN KEY(ID_CARD) REFERENCES CARDS(ID)

);

--STORED PROCEDURES
--INSERT NEW CREDIT CARD
CREATE PROCEDURE GET_ACCOUNTBALANCE
(
	@CARD_NUMBER NVARCHAR(20) ,
	@ID_TARJETA UNIQUEIDENTIFIER 
)
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @INTEREST_BON DECIMAL(18,2);
	
	BEGIN TRY

		IF NOT EXISTS (
            SELECT 1 FROM CARDS 
            WHERE (@ID_TARJETA IS NULL OR ID = @ID_TARJETA)
              AND (@CARD_NUMBER IS NULL OR LASTD_CARD = @CARD_NUMBER)
        )
        BEGIN
            THROW 50001, 'Card not found', 1;
        END

		SELECT 
			TOTAL_CREDIT, AV_CREDIT, CREDIT_LIMIT,
			(TOTAL_CREDIT * (INTEREST/100)) AS INTERES_BONIFICABLE,
			(TOTAL_CREDIT * (MIN_INTEREST/100)) AS MIN_PAYMENT,
			TOTAL_CREDIT AS TOTAL_AMOUNT_TO_PAY,
			(TOTAL_CREDIT + (TOTAL_CREDIT * (INTEREST/100))) AS TOTAL_AMOUNT_WITH_INTEREST
		FROM CARDS
		WHERE ID = @ID_TARJETA AND LASTD_CARD = @CARD_NUMBER;

	END TRY
	BEGIN CATCH
        THROW;
    END CATCH
END
GO

