USE BD_TARJETA;
GO

-- TABLE CREATION
CREATE TABLE LOGS(

	ID INT IDENTITY(1,1) PRIMARY KEY ,  
	ORIGIN NVARCHAR(100) NOT NULL,
	LOG_DESCRIPTION NVARCHAR(600) NULL,
	LOG_DT  DATETIME2 DEFAULT GETDATE()
);

CREATE TABLE DOCTYPE(

	ID INT IDENTITY(1,1) PRIMARY KEY,
	DOCNAME NVARCHAR(30) NOT NULL

);

CREATE TABLE TRANSACTION_STATE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TSTATE NVARCHAR(50) NOT NULL
);

CREATE TABLE CLIENT(
	DOC_NUMBER NVARCHAR(20) NOT NULL PRIMARY KEY,
	CLIENT_NAME NVARCHAR(250) NOT NULL,
	CELLPHONE NVARCHAR(100) NULL,
	EMAIL NVARCHAR(200) NULL,
	CREATION_DATE  DATETIME2 DEFAULT GETDATE(),
	CREATION_USER NVARCHAR(100) DEFAULT 'SYSTEM',
	ID_DOCTYPE INT NOT NULL,
	CONSTRAINT FK_CLIENT_DOCTYPE FOREIGN KEY (ID_DOCTYPE) REFERENCES DOCTYPE(ID)
);



CREATE TABLE CARDS(

	ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	ID_CLIENT NVARCHAR(20) NOT NULL,
	CARD_NUMBER NVARCHAR(20) NOT NULL,
	LASTD_CARD VARCHAR(4) NOT NULL,
	CREDIT_LIMIT DECIMAL(18,2) NOT NULL,
	AV_CREDIT DECIMAL(18,2) NOT NULL,
	TOTAL_CREDIT DECIMAL(18,2) NOT NULL,
	INTEREST DECIMAL(18,2) DEFAULT 9.0,
	MIN_INTEREST DECIMAL(18,2) DEFAULT 5.0,
	CREATION_DATE DATETIME2 DEFAULT GETDATE(),
	CREATION_USER VARCHAR(100) DEFAULT 'SYSTEM',
	CONSTRAINT FK_ID_CLIENTE_CC FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(DOC_NUMBER)

)


CREATE TABLE MOVEMENTS_TC(

	ID INT IDENTITY(1,1) PRIMARY KEY,
	MV_DATE DATETIME2 NOT NULL DEFAULT GETDATE(),
	ID_CARD UNIQUEIDENTIFIER NOT NULL, 
	AMOUNT DECIMAL(18,2) NOT NULL,
	MV_DESCRIPTION NVARCHAR(300) NULL,
	ID_STATE INT NOT NULL,
	CONSTRAINT FK_ID_STATE_MV FOREIGN KEY(ID_STATE) REFERENCES TRANSACTION_STATE(ID),
	CONSTRAINT FK_ID_CARD_MV FOREIGN KEY(ID_CARD) REFERENCES CARDS(ID)

);

CREATE TABLE PAYMENTS_TC(

	ID INT IDENTITY(1,1) PRIMARY KEY,
	MV_DATE DATETIME2 NOT NULL DEFAULT GETDATE(),
	ID_CARD UNIQUEIDENTIFIER NOT NULL, 
	AMOUNT DECIMAL(18,2) NOT NULL,
	MV_DESCRIPTION NVARCHAR(300) NULL,
	ID_STATE INT NOT NULL,
	CONSTRAINT FK_ID_STATE_PY FOREIGN KEY(ID_STATE) REFERENCES TRANSACTION_STATE(ID),
	CONSTRAINT FK_ID_CARD_PY FOREIGN KEY(ID_CARD) REFERENCES CARDS(ID)

);

--STORED PROCEDURES
--INSERT NEW CREDIT CARD
CREATE PROCEDURE GET_CLIENTWITHCARDS
(
	@CLIENT NVARCHAR(20)
)
AS
BEGIN
	SET NOCOUNT ON
	BEGIN TRY

		SELECT CL.DOC_NUMBER, CL.CLIENT_NAME, CD.CARD_NUMBER  FROM CLIENT AS CL
		INNER JOIN CARDS AS CD
		ON CL.DOC_NUMBER = CD.ID_CLIENT
		WHERE DOC_NUMBER = @CLIENT;

	END TRY
	BEGIN CATCH
		THROW
	END CATCH
END

CREATE PROCEDURE GET_ACCOUNTBALANCE
(

	@ID_TARJETA UNIQUEIDENTIFIER 
)
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @INTEREST_BON DECIMAL(18,2);
	
	BEGIN TRY

		IF NOT EXISTS (
            SELECT 1 FROM CARDS 
            WHERE (@ID_TARJETA IS NULL OR ID = @ID_TARJETA)
              AND (@CARD_NUMBER IS NULL OR LASTD_CARD = @CARD_NUMBER)
        )
        BEGIN
            THROW 50001, 'Card not found', 1;
        END

		SELECT 
			TOTAL_CREDIT, AV_CREDIT, CREDIT_LIMIT,
			(TOTAL_CREDIT * (INTEREST/100)) AS INTERES_BONIFICABLE,
			(TOTAL_CREDIT * (MIN_INTEREST/100)) AS MIN_PAYMENT,
			TOTAL_CREDIT AS TOTAL_AMOUNT_TO_PAY,
			(TOTAL_CREDIT + (TOTAL_CREDIT * (INTEREST/100))) AS TOTAL_AMOUNT_WITH_INTEREST
		FROM CARDS
		WHERE ID = @ID_TARJETA AND LASTD_CARD = @CARD_NUMBER;

	END TRY
	BEGIN CATCH
        THROW;
    END CATCH
END
GO

CREATE PROCEDURE PROCESS_PURCHASE
(
    @ID_TARJETA UNIQUEIDENTIFIER,
    @MONTO DECIMAL(18,2),
    @DESCRIPCION NVARCHAR(200),
    @FECHA DATETIME,
	@PurchaseId INT OUTPUT,
	@Status INT OUTPUT
)
AS
BEGIN
     SET NOCOUNT ON;
    DECLARE @RowsAffected INT;

    BEGIN TRY
        BEGIN TRANSACTION;

        UPDATE CARDS
        SET AV_CREDIT = AV_CREDIT - @MONTO,
            TOTAL_CREDIT = TOTAL_CREDIT + @MONTO
        WHERE ID = @ID_TARJETA
          AND CARD_STATUS = 'ACTIVE'
          AND AV_CREDIT >= @MONTO;

        SET @RowsAffected = @@ROWCOUNT;

        SET @Status = CASE WHEN @RowsAffected = 0 THEN 4 ELSE 3 END;

        INSERT INTO MOVEMENTS_TC (ID_CARD, MV_DATE, AMOUNT, MV_DESCRIPTION, ID_STATE)
        VALUES (@ID_TARJETA, @FECHA, @MONTO, @DESCRIPCION, @Status);

        SET @PurchaseId = SCOPE_IDENTITY();

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END
GO


--INSERTS
INSERT INTO TRANSACTION_STATE
VALUES 
	('Pending'),
	('In Progress'),
	('Finished'),
	('Failed');


SELECT * FROM TRANSACTION_STATE;
SELECT * FROM DOCTYPE;

INSERT INTO DOCTYPE
VALUES 
	('DUI'),
	('NIT')